# action.yaml
name: "Blog Custom Github Action"
description: "Call an API and get the result"
inputs:
  urls:
    description: "urls to test"
    required: true
    default: '[]'
outputs:
  status_codes:
    description: "returned codes"
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.urls }}
