name: "HTTP Checker"
description: "Checks the http status of websites"
inputs:
  urls:
    description: "urls to test"
    required: true
    default: "[]"
outputs:
  responses:
    description: "responses to get requests"
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.urls}}
