name: 'Test Action'
description: 'Tests my capability to think'
inputs:
  x:
    description: 'a number'
    required: true
    default: 1
outputs:
  y:
    description: 'another number'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.x }}