name: Tester

on:
  workflow_dispatch:

jobs:
  Test:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - name: Test this action
        uses: ./@master
        id: action
        with:
          urls: '["test1", "test2"]'
          coses: '[100, 200]'

      - name: Print outpuot
        run: echo "${{ steps.action.outputs.status }}"