on: [push]

jobs:
  custom_test:
    runs-on: ubuntu-latest
    name: We test it locally with act
    steps:
      - name: Get Pokemon name
        uses: ./
        id: test
        with:
          urls: '["test1", "test2"]'
      - name: print out
        run: echo "${{ steps.test.outputs.status_codes }} BITCH!"
