on: [push]

jobs:
  custom_test:
    runs-on: ubuntu-latest
    name: Test the http-checker
    steps:
      - name: Get responses
        uses: lennart1s/http-checker@v2
        id: tester
        with:
          urls: "[5, 6, 10]"
      - name: Print results
        run: echo "Results ${{ steps.tester.outputs.responses }}"
