on: [push]

jobs:
  custom_test:
    runs-on: ubuntu-latest
    name: Test the http-checker
    steps:
      - name: Get responses
        uses: lennart1s/http-checker@v2
        id: tester
        with:
          urls: "[\"https://google.com\", \"https://sandbothe.dev\"]"
          codes: "[200, 301, 503]"
      - name: Print results
        run: echo "${{ steps.tester.outputs.responses }}"
